### ISSUE TITLE
📦 NEW: Gif demo

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/Shades-of-Purple-Konsole#2]
>Thanks for creating a theme for Konsole @rahilwazir 🙌
Creating a few issues to address things I think should be fixed.

Add a gif demo using CloudApp you can find the link to it on https://ahmadawais.com/uses/

Also make sure that you open this [white image](http://on.ahmda.ws/qZxX/c) in the bg and then center the Konsole window so that it looks neat — have about 1.5 inches of white bg from all borders — just like in my gif.

**Comment by rahilwazir** [comment]
Can't we use this for time being?

![shades-of-purple-konsole-demo](https://user-images.githubusercontent.com/1818941/38187556-918a76ae-3671-11e8-882c-2139c249a404.gif)

I use [i3wm](https://i3wm.org/) and it does not support maximize/restore option since its a tiling manager. I will have to switch to another desktop manager to create similar demo as you've described but it might take some days because I have running applications on my current setup before I switch (log off).

Also the CloudApp does not support ingenious Linux :stuck_out_tongue_closed_eyes:

<p align="center">
<img src="https://user-images.githubusercontent.com/1818941/38174427-41f91e78-35e6-11e8-8e59-780e0227060b.png">
</p>

**Comment by ahmadawais** [comment]
@rahilwazir we can use that. Just commit it and we're good to go.

**Comment by rahilwazir** [comment]
Done :tada: :raised_hands:
